language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/cibuild 

script: ./script/cibuild

# Branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  
# Only build the latest commit
git:
  depth: 1
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false