language: ruby

sudo: false

cache:
  bundler: true
  directories:
    - vendor/bundle

rvm:
  - &ruby23 2.3
  
before_script:
  - chmod +x ./script/cibuild 

script: ./script/cibuild

branches:
  only:
  - master
  
git:
  depth: 1
