# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Esports Kingdom
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://esportskingdom.nz" # the base hostname & protocol for your site
permalink: /:categories/:year/:month/:title.html

# Social Link #
footer-links:
  email: grady.hooker8@gmail.com
  github: GradyHooker
  rss: "" # just type anything here for a working RSS icon
  twitter: GradyHooker

# Pagination #
pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num'
  title: 'Page :num of :max'
  limit: 0
  sort_field: 'circa'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor